### ISSUE TITLE
thermostat Plugin for Honeywell

### ISSUE THREAD

**Issue by donavanbecker** [Supereg/homebridge-http-temperature-sensor#10]
Hey,

I see you do a lot of typescript, what are the chances of creating a HomeBridge plugin for Honeywell lyric thermostats?

**Comment by donavanbecker** [comment]
All the ones out there don’t work for Honeywell Lyric Thermostats

**Comment by bauer-andreas** [comment]
Not really realistic I guess. I don't own Honeywell Thermostats, so developing for them isn't really easy when I can't really test my code.
Additionally is it even possible to interface with those thermostats. Does the Honeywell Thermostat expose any API someone could use to make such a plugin?

**Comment by donavanbecker** [comment]
https://developer.resideo.com & https://developer.honeywellhome.com

You can use my thermostat...

**Comment by bauer-andreas** [comment]
To give some updates. There are currently no plans from my side to create a plugin like this.
I don't own them so I'm not really interested to put time into it (simply speaking). I currently do not have the time for side projects like this 😅 There are too much other projects I would rather work end but also will probably never have enough time for them 😅 
So closing this issue for now
