### ISSUE TITLE
Can't get temperature value

### ISSUE THREAD

**Issue by Zolpho** [Supereg/homebridge-http-temperature-sensor#12]
Hello,

I'm trying to get the temperature value from my myStrom motion sensor.
Here's the API > https://api.mystrom.ch/?version=latest#95d8103e-db16-4383-b141-8e93afef0bbd
and here's my code:

`{
            "accessory": "HTTP-TEMPERATURE",
            "name": "Bath Temp",
            "getUrl": {
                "url": "http://192.168.1.241/api/v1/sensors",
                "method": "GET",
                "statusPattern": "\"temperature\":([0-9]{2})",
                "pullInterval": 30,
                "debug": true
            }`
Not sure if my pattern is correct.
I have no error logs to share, there's none and debug on is not making any difference.

Thanks for helping :)
Zolpho

**Comment by markavitale** [comment]
Not involved in this project, although I just installed it on my home bridge. For generating my regex pattern, I found https://regexr.com useful. I pasted in the sample response from my temperature sensor, and then built the regex and confirmed it was matching the exact temperature I wanted.
