### ISSUE TITLE
Consistency with units?

### ISSUE THREAD

**Issue by jlg89** [Supereg/homebridge-http-temperature-sensor#15]
The temperature displayed in HomeKit is always Celsius.

For maximum functionality, it would be preferable to have an additional configuration option, maybe "displayUnit," that would control what units are supplied to HomeKit. So, "unit" would tell the plugin whether it's reading C or F from the source, and "displayUnit" would tell the plugin whether to send C or F values to HomeKit.

At the very least, if "unit" is set to "fahrenheit" then those units should be passed straight to HomeKit. Less functional, but at least consistent.

**Comment by bauer-andreas** [comment]
The HomeKit protocol will always just transmit temperature in Celsius. It’s up to the home app (or the configured phone) to display Fahrenheit.

**Comment by jlg89** [comment]
Well dang it, it just changed. When I first configured the plugin, the temp in the Home app displayed in Celsius, and now it's Fahrenheit. Oh well, chalk up another one for the tech gnomes.

Thanks for the fast response, anyway. Sorry to have troubled you.

**Comment by bauer-andreas** [comment]
all fine, happy you find the solution 😅
