### ISSUE TITLE
- HomeKit accessory converts temperature value to Celsius automatically via this plugin.

### ISSUE THREAD

**Issue by lemonkey** [Supereg/homebridge-http-temperature-sensor#4]
You may want to mention this in the docs :)

**Comment by bauer-andreas** [comment]
The README explicitly states that the “getUrl” expects a temperature in Celsius.
I’m not quite sure what you are referring to.
If you want to switch to Fahrenheit you need to do that in the Home App 🤔

**Comment by lemonkey** [comment]
My mistake. :)
