### ISSUE TITLE
Last version not working

### ISSUE THREAD

**Issue by netRunner0** [Supereg/homebridge-http-temperature-sensor#5]
Hey. What has changed in the latest version? The plugin has stopped working, gives an error:
![f905a2bf-312b-4c6a-ac2b-e40a22790fd6](https://user-images.githubusercontent.com/44049295/53825284-bf15cf80-3f97-11e9-9874-c24f2b1b8d2b.png)

`      {
            "accessory": "HTTP-TEMPERATURE",
            "name": "iKettle 2.0t",
            "pullInterval": 5000,
            "getUrl": "http://10.0.0.100:2080/api/10.0.0.13/raw/temperature"
        },`

I did not change my configuration. By reference from the configuration, I still see the temperature.

![e8dd7fc6-650a-4ef8-b335-709d65d5144e](https://user-images.githubusercontent.com/44049295/53825442-19169500-3f98-11e9-9199-e8ac8920d701.png)

**Comment by bauer-andreas** [comment]
Sorry for the inconvenience, there was an error in the default pattern which gets matched against the body of the http response. Is now fixed in the latest version v1.0.3
