### ISSUE TITLE
Temperature precision

### ISSUE THREAD

**Issue by vigorem** [Supereg/homebridge-http-temperature-sensor#8]
Hi,

I'm loading temperature from my local server and successfully added the accessory to homebridge.

However a temperature of `10.3125` will display as `10.5`on my iPhone.

I though I could change the `statusPattern` to : `(-?[0-9]{0,3}(\.[0-9][0-9])?)` so I could get a 2 digits precision (`10.31`) but this was uneffective.

Do you have any tips for that?

thanks,

Sébastien

**Comment by bauer-andreas** [comment]
This is a limitation of HomeKit. HomeKit does only display the temperature in 0.5 steps.

**Comment by vigorem** [comment]
Thanks, wasn't aware of that
